name: roomie_tasks
description: Roomie Tasks
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.0
  go_router: ^14.2.7
  gsheets: ^0.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  provider: ^6.1.2
  uuid: ^4.5.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
  