version: '3'

tasks:

  default:
    summary: |
      Just a list of documented tasks.
    silent: true
    cmds:
      - task --list

  check:
    desc: Checks
    deps:
      - get
      - format
      - analyze

  get:
    desc: Install Flutter dependencies
    cmds:
      - flutter packages get

  format:
    desc: Dark format
    cmds:
      - dart format .

  analyze:
    desc: Run Flutter analyze
    cmds:
      - flutter analyze

  br:
    desc: dart run build_runner build
    cmds:
      - dart run build_runner build --delete-conflicting-outputs

  build:apk:
    desc: Build for Android
    cmds:
      - flutter build apk --flavor production --target lib/main_production.dart
  
  build:appbundle:
    desc: Build for Android (App Bundle)
    cmds:
      - flutter build appbundle --flavor production --target lib/main_production.dart


  build:ipa:
    desc: Build an IPA (iOS)
    cmds:
      - flutter build ipa --release --flavor production --target lib/main_production.dart

  dev:
    desc: Run the development flavor
    cmds:
      - flutter run --flavor development --target lib/main_development.dart

  staging:
    desc: Run the staging flavor 
    cmds:
      - flutter run --flavor staging --target lib/main_staging.dart

  production:
    desc: Run the production flavor
    cmds:
      - flutter run --flavor production --target lib/main_production.dart

  test:
    desc: Run unit and widget tests with coverage
    cmds:
      - flutter test --coverage --test-randomize-ordering-seed random

  coverage:
    desc: Generate and open a coverage report
    cmds:
      - genhtml coverage/lcov.info -o coverage/
      - open coverage/index.html